- name: Create teacher user
  user:
    name: teacher
    password: "{{ '12345678' }}"
    shell: /bin/bash
    groups: sudo
    append: true

- name: Create operator user
  user:
    name: operator
    password: "{{ '12345678' }}"
    shell: /bin/bash
  when: "'workers' in group_names"

- name: Create app user
  user:
    name: app
    shell: /usr/sbin/nologin
    system: true
  when: "'workers' in group_names"

- name: Configure operator sudo
  template:
    src: operator-sudo.j2
    dest: /etc/sudoers.d/operator
    mode: "0440"
