- name: Install base packages
  apt:
    name:
      - curl
      - git
      - nginx
      - sudo
    state: present
    update_cache: true

- name: Create student user
  user:
    name: student
    create_home: yes

- name: Create student group
  group:
    name: student
    state: present

- name: Create student home directory
  file:
    path: /home/student
    state: directory
    owner: student
    group: student
    mode: "0755"

- name: Create gradebook file
  copy:
    dest: /home/student/gradebook
    content: "{{ gradebook_number }}"
    owner: root
    group: root
    mode: "0644"
