- name: Install base packages
  apt:
    name:
      - curl
      - git
      - nginx
      - sudo
    state: present
    update_cache: true

- name: Create gradebook file
  copy:
    dest: /home/student/gradebook
    content: "{{ gradebook_number }}"
    owner: root
    group: root
    mode: "0644"
